// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCudmdNsfAYhmLOgNvc6PzdKtUXhZlFQXc",
      authDomain: "flash-chat-54078.firebaseapp.com",
      projectId: "flash-chat-54078",
      storageBucket: "flash-chat-54078.firebasestorage.app",
      messagingSenderId: "917673730443",
      appId: "1:917673730443:web:1ea93ccf6f7d25acdfcf8e"
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyCudmdNsfAYhmLOgNvc6PzdKtUXhZlFQXc",
      authDomain: "flash-chat-54078.firebaseapp.com",
      projectId: "flash-chat-54078",
      storageBucket: "flash-chat-54078.firebasestorage.app",
      messagingSenderId: "917673730443",
      appId: "1:917673730443:web:1ea93ccf6f7d25acdfcf8e"
  );

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: "AIzaSyCudmdNsfAYhmLOgNvc6PzdKtUXhZlFQXc",
      authDomain: "flash-chat-54078.firebaseapp.com",
      projectId: "flash-chat-54078",
      storageBucket: "flash-chat-54078.firebasestorage.app",
      messagingSenderId: "917673730443",
      appId: "1:917673730443:web:1ea93ccf6f7d25acdfcf8e"
  );

  static const FirebaseOptions macos = FirebaseOptions(
      apiKey: "AIzaSyCudmdNsfAYhmLOgNvc6PzdKtUXhZlFQXc",
      authDomain: "flash-chat-54078.firebaseapp.com",
      projectId: "flash-chat-54078",
      storageBucket: "flash-chat-54078.firebasestorage.app",
      messagingSenderId: "917673730443",
      appId: "1:917673730443:web:1ea93ccf6f7d25acdfcf8e"
  );

  static const FirebaseOptions windows = FirebaseOptions(
      apiKey: "AIzaSyCudmdNsfAYhmLOgNvc6PzdKtUXhZlFQXc",
      authDomain: "flash-chat-54078.firebaseapp.com",
      projectId: "flash-chat-54078",
      storageBucket: "flash-chat-54078.firebasestorage.app",
      messagingSenderId: "917673730443",
      appId: "1:917673730443:web:1ea93ccf6f7d25acdfcf8e"
  );
}