// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF8S56Rc38YLKYZboK9hezrNmrodwuUbU',
    appId: '1:836925497596:web:0c417643ab110cfb2fb779',
    messagingSenderId: '836925497596',
    projectId: 'flash-chat-14378',
    authDomain: 'flash-chat-14378.firebaseapp.com',
    storageBucket: 'flash-chat-14378.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5i3rSWiPTqFJjtK_i4VzbPFIzh0ituQU',
    appId: '1:836925497596:android:c45d2aeec5ed76592fb779',
    messagingSenderId: '836925497596',
    projectId: 'flash-chat-14378',
    storageBucket: 'flash-chat-14378.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLkb_ywUZlTzxLslrsrF7GAdB4hqtluQc',
    appId: '1:836925497596:ios:c35a8e11e0618ebe2fb779',
    messagingSenderId: '836925497596',
    projectId: 'flash-chat-14378',
    storageBucket: 'flash-chat-14378.firebasestorage.app',
    iosBundleId: 'com.example.flashChatStartingProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLkb_ywUZlTzxLslrsrF7GAdB4hqtluQc',
    appId: '1:836925497596:ios:c35a8e11e0618ebe2fb779',
    messagingSenderId: '836925497596',
    projectId: 'flash-chat-14378',
    storageBucket: 'flash-chat-14378.firebasestorage.app',
    iosBundleId: 'com.example.flashChatStartingProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF8S56Rc38YLKYZboK9hezrNmrodwuUbU',
    appId: '1:836925497596:web:21a8600f59619a0f2fb779',
    messagingSenderId: '836925497596',
    projectId: 'flash-chat-14378',
    authDomain: 'flash-chat-14378.firebaseapp.com',
    storageBucket: 'flash-chat-14378.firebasestorage.app',
  );
}